
name: wordpress-calismalari

services:
  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress-calismalari-wp
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-calismalari-mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    volumes:
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress_network
    depends_on:
      - wordpress-calismalari-mysql

  # MySQL Database
  wordpress-calismalari-mysql:
    image: mysql:8.0
    container_name: wordpress-calismalari-mysql
    user: "1000:1000"
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./wordpress-db-data:/var/lib/mysql
      - ./config/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - wordpress_network
    command: --default-authentication-plugin=mysql_native_password

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress-db-data:
